### ISSUE TITLE
new team mochiling members

### ISSUE THREAD

**Issue by esmochiling** [xavijam/mochiling#14]
- añadir info/videos/RRSS de 

charly
jonkita
frodo

**Comment by xavijam** [comment]
Necesito info de cada uno:

- Descripción corta.
- Descripción "larga".
- Paises visitados.
- Nombre.
- Lenguas que hablan.
- Instagram
- Facebook
- Twitter

**Comment by esmochiling** [comment]
como te dije esto me enseñaras la próxima vez que nos veamos y así molesto lo menos posible

**Comment by esmochiling** [comment]
hay que linkear el video de mushroom shakes ala bio de panozzo
