### ISSUE TITLE
dar una vuelta a las frases para pagina de error

### ISSUE THREAD

**Issue by esmochiling** [xavijam/mochiling#18]
ingles y español.

www.mochiling.es/perico

**Comment by esmochiling** [comment]
Viajar es la mejor manera de perderse, para encontrarse.
Traveling is the best way to get lost, to/and find yourself.

En ocasiones lo mejor es perderse, para encontrar un camino mejor.
Sometimes getting lost is the way to find a better path.

Nadie encuentra su camino, sin perderse varias veces.
No one finds his path, without getting lost several times.


me gustan las tres ...que te parece???se podrían poner las tres indistintamente???si fuera así  genial sino creo que la primera es la que mas pega...no??como ves las traducciones(to /and)???

**Comment by xavijam** [comment]
Me encanta la primera la verdad, la meto y si quieres vamos viendo.
