### ISSUE TITLE
Create homepage

### ISSUE THREAD

**Issue by xavijam** [xavijam/mochiling#2]
- [x] Improve title (remove ·). 
- [x] Fix header selected state.
- [x] Change slider buttons color (orange? white?)
- [x] Add final images.
- [x] Review texts (@esmochiling).
- [x] Finish proposals block.
- [x] Fix member link.

**Comment by xavijam** [comment]
Esto está casi casi por mi parte -> [mochiling.es](http://mochiling.es)

**Comment by xavijam** [comment]
He puesto en la cabecera lo que me falta de la home.

**Comment by esmochiling** [comment]
te paso por mail las fotos mas guapas...

**Comment by xavijam** [comment]
Queda pendiente tus textos amigo.

**Comment by esmochiling** [comment]
textos???en la portada??? creo que esto esta finiquitado, quitando lo de la version movil y sus flechitas...

este issue lo cerramos juntos cuando nos veamos...
