### ISSUE TITLE
Add Europe experience

### ISSUE THREAD

**Issue by xavijam** [xavijam/mochiling#4]

**Comment by xavijam** [comment]
<img width="539" alt="proposals" src="https://user-images.githubusercontent.com/132146/32389170-369f9eda-c0ca-11e7-8a23-b7a469fbae53.png">

**Comment by esmochiling** [comment]
Europa

texto: Si lo que buscais es conocer Europa de una forma diferente, nuestros guias mochiling, con mas de 10 años de experiencia, te ayudaran a montar un viaje único. 

https://youtu.be/09Xjt3SCoMw

**Comment by xavijam** [comment]
- Texto corto
- Imagen principal (desde instagram mejor).
- Hashtag para instagram
- Video: https://youtu.be/09Xjt3SCoMw
- Paises.
- Texto largo: Si lo que buscais es conocer Europa de una forma diferente, nuestros guias mochiling, con mas de 10 años de experiencia, te ayudaran a montar un viaje único.
- Fechas

**Comment by esmochiling** [comment]
#mochilingeurope

**Comment by esmochiling** [comment]
Texto corto: Europa desde todos los puntos de vista- Europe from all points of view

Imagen principal (desde instagram mejor).

Hashtag para instagram: #mochilingeurope

Video: https://youtu.be/09Xjt3SCoMw

Países.(yo marcaria toda europa)

Texto largo: Si lo que buscais es conocer Europa de una forma diferente, nuestros guias mochiling, con mas de 10 años de experiencia, te ayudaran a montar un viaje único.-
If you want to visit Europe in a different way, our mochiling guides, with more than a decade of experience, will help you to make a unique trip.

Fechas 2010-2XXX

**Comment by esmochiling** [comment]
pendiente de que dani me mande si texto largo....

**Comment by esmochiling** [comment]
te mande la foto  de la imagen principal por whatssapp...si lo mismo es mas fácil...es la primera q sale si pones en google: viajes por europa

**Comment by esmochiling** [comment]
puse alguna fotos con hashtag #mochilingeurope ...coge cual quieras...pa no poner la que te mande por whatssapp

**Comment by xavijam** [comment]
Hecho, el tema es que no he puesto todos todos todos los paises europeos como marcados. Me he dejado fuera a los escandinavos y al Ruuuuso. Si crees que tienen que estar todos avisa y los ponemos.
