### ISSUE TITLE
Arreglar textos Alaska /Korea english

### ISSUE THREAD

**Issue by esmochiling** [xavijam/mochiling#5]
KOREA:
The mixture between the traditions and the modern world is a feeling that involves you during your stay in Korea. The huge Seoul, the Busan beaches and the interior mountains.
A real korean experience with my friend and part of ·teammochiling; @Daniel Panozzo.
Unknown place, different culture, incredible gastronomy, good music scene…what more can i ask for???

ALASKA La magia Congelada/ The frozen magic

Alaska es distinta de cualquier otro destino del mundo. Cada día brinda un recuerdo imborrable: Hacer snowboard, literalmente hasta el Pacifico, conducir por las heladas carreteras, glaciares y montañas, culturas nativas únicas en un marco absolutamente incomparable.

Alaska is different from every other destination in the world. Every day offers an unforgettable memory: Snowboarding until the Pacific shore, drive through the icy roads, glaciers and mountains, unique Native cultures, in a absolutely incomparable frame.

**Comment by xavijam** [comment]
Added
