### ISSUE TITLE
Check logo for most visited websites

### ISSUE THREAD

**Issue by esmochiling** [xavijam/mochiling#6]

**Comment by xavijam** [comment]
https://realfavicongenerator.net/blog/apple-touch-icon-the-good-the-bad-the-ugly/

**Comment by esmochiling** [comment]
no entiendo muy bien...te puedo ayudar con algo en esta tarea???

**Comment by xavijam** [comment]
Na, eso es para mí, que ya sé como arreglarlo ;).

**Comment by esmochiling** [comment]
aqui hay que revisar diferentes plataformas ..porque me sale en android pero no en el mac...
