### ISSUE TITLE
PROPOSALS

### ISSUE THREAD

**Issue by esmochiling** [xavijam/mochiling#7]
-Cambiar color

-en la parte ingles. no funcionan las traducciones

-buscar display para nueva organización de diferentes proposals.
![20171103_193557](https://user-images.githubusercontent.com/23558421/32390429-b5114b3e-c0ce-11e7-8bd0-a9563be93eea.jpg)

**Comment by xavijam** [comment]
uoh!, qué es esto? :D

**Comment by esmochiling** [comment]
a falta de buscar una alternativa para el botón de cara a cara...esta parte  finiquitado

**Comment by esmochiling** [comment]
le he dado una vuelta a la pagina entera de propuestas...a ver que te parece??

-primero creo que el color que elegimos para propuestas y experiencias es muy ROJO y debería ser que se viese mas naranja....se puede???

en el texto del encabezado:

¿Como prefieres viajar?Queremos que disfrutes de una experiencia Mochiling, es nuestro objetivo,echa un ojo a nuestras propuestas. (FUERA DESDE NADA DE AGENCIAS...HASTA EL FINAL)

En el apartado en ingles de mochiling no me suena del todo bien lo de "trip IN something..."

en los 6 epígrafes algunos cambios:

- experiencia unica: cambiarle el logo. eligelo tu...
-contacto: poner vector de información (la típica i de información)
                   el texto seria "pregunta a los miembros de teammochiling por tu proximo viaje" 
                                          "ask the members of teammochiling about your next trip"
-experto mochiling: en el texto cambiar experto por guias(en english expert por guides)
-cara a cara: poner el logo que tenia la experiencia única
                      el titulo sera "A LA CARTA"
                      el texto sera "Tu decides, nosotros conseguimos"
-servicio al viajero: quitar el 24/7 (tb en english)
-seguro de viaje:  esta perfect¡¡¡¡
